[package]
name = "pagelist-bot"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plbot_parser = { path = "parser", version = "0.0.1" }
mediawiki = "^0.2"
