[package]
name = "plbot_solver"
version = "0.0.1"
edition = "2021"

license = "MIT"

[dependencies]
plbot_base = { path = "../base" }
mediawiki = "^0.2"
serde_json = { version = "^1.0" }

[features]
default = [ "mwapi" ]
mwapi = [ ]
