[package]
name = "plbot_solver"
version = "0.0.1"
edition = "2021"

license = "MIT"

[dependencies]
mediawiki = { version = "^0.2", optional = true }

[features]
default = ["mwapi"]
mwapi = ["mediawiki"]