name: Build Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/*'
      - '!.github/workflows/test.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/*'
      - '!.github/workflows/test.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
